default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: back_end_development

test:
  <<: *default
  database: back_end_test

production:
  primary: &primary_production
    <<: *default
    database: back_end_production
    username: back_end
    password: <%= ENV["BACK_END_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: back_end_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: back_end_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: back_end_production_cable
    migrations_paths: db/cable_migrate
